Repository dandi/dandi-schema, pull requests merged in 2021-09, with the labels that each got.

#56 Switch to versioningit (non-src-layout)
  .github/workflows/test-dandi-cli.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  MANIFEST.in
  dandischema/__init__.py
  dandischema/_version.py
  pyproject.toml
  setup.cfg
  setup.py
  tox.ini
  versioneer.py
Labels: internal

#81 fixing to_datacie, allowing for None in roleName
  dandischema/datacite.py
  dandischema/tests/test_datacite.py
Labels: patch, release

#83 remove NC license
  dandischema/consts.py
  dandischema/model_types.py
  dandischema/tests/test_models.py
Labels: patch, release

#86 Release 0.6.0
  README.md
Labels: minor, release

#89 Better exception classes
  dandischema/exceptions.py
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
Labels: enhancement, patch, release
