Repository dandi/dandi-schema, pull requests merged in 2021-06, with the labels that each got.

#28 fix: remove readOnly from constants
  dandischema/consts.py
  dandischema/models.py
Labels: patch, release

#31 Use DANDI_GITHUB_TOKEN to check out dandi/schema when releasing
  .github/workflows/release.yml
Labels: internal

#30 fix: update migration code to account for missing fields
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_utils.py
  dandischema/utils.py
Labels: patch, release

#33 Allow location fields to have localhost URLs
  dandischema/models.py
Labels: patch, release

#37 Only attempt to remove contributorType if present
  dandischema/datacite.py
Labels: bug

#34 enh: implement metadata aggregator for asset summary
  dandischema/consts.py
  dandischema/metadata.py
  dandischema/models.py
  dandischema/tests/data/metadata/asset3_01.json
  dandischema/tests/data/metadata/asset3_02.json
  dandischema/tests/data/metadata/asset4_01.json
  dandischema/tests/data/metadata/asset4_02.json
  dandischema/tests/test_metadata.py
Labels: patch, release

#38 fix: make assetsummary computable for dandisets with no assets
  dandischema/consts.py
  dandischema/metadata.py
  dandischema/models.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
Labels: patch, release

#40 fix: allow migration for versions greater than 0.3.2
  dandischema/consts.py
  dandischema/metadata.py
Labels: patch, release

#41 Fix: Make the library more robust for publishing
  dandischema/datacite.py
  dandischema/models.py
  dandischema/tests/test_datacite.py
  dandischema/tests/test_models.py
Labels: patch, release

#39 Add flake8 to .pre-commit-config.taml
  .pre-commit-config.yaml
Labels: internal

#42 enh: update models to do more validation checks
  dandischema/consts.py
  dandischema/models.py
  dandischema/tests/data/metadata/meta_000004.json
  dandischema/tests/data/metadata/meta_000004old.json
  dandischema/tests/data/metadata/meta_000008.json
  dandischema/tests/test_datacite.py
  dandischema/tests/test_models.py
Labels: patch, release

#44 release.yml: Use DANDI_GITHUB_TOKEN to push to repo
  .github/workflows/release.yml
Labels: internal, patch, release

#45 doc: add a bit more info to readme
  README.md
Labels: patch, release

#48 enh: allow checking to see data are matched but allow for missing fields
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
Labels: patch, release
