Repository dandi/dandi-schema, pull requests merged in 2021-05, with the labels that each got.

#1 Start CHANGELOG
  CHANGELOG.md
Labels: documentation

#8 Include CHANGELOG.md and tox.ini in sdists
  MANIFEST.in
Labels: internal

#10 Pin auto version
  .github/workflows/release.yml
Labels: internal

#11 RF(TEMP): disable publishing new versions of schemata
  .github/workflows/publish-schemata.yml
Labels: internal, release

#6 ENH: support migration, validation, schema improvements
  .github/workflows/test.yml
  dandischema/__init__.py
  dandischema/consts.py
  dandischema/datacite.py
  dandischema/metadata.py
  dandischema/model_types.py
  dandischema/models.py
  dandischema/tests/data/metadata/asset_001.json
  dandischema/tests/data/metadata/meta_000004.json
  dandischema/tests/data/metadata/meta_000004old.json
  dandischema/tests/data/metadata/meta_000008.json
  dandischema/tests/test_datacite.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
  dandischema/tests/test_utils.py
  dandischema/utils.py
  setup.cfg
  tox.ini
Labels: minor, release

#20 Patch versioneer to exclude tags that don't start with a digit
  dandischema/_version.py
  versioneer.py
Labels: internal

#17 Set up schema testing and autorelease of new schemata
  .autorc
  .github/workflows/publish-schemata.yml
  .github/workflows/release.yml
  .github/workflows/test-schema.yml
Labels: tests

#24 fix: dandi-etag carries extra component beyond md5
  dandischema/models.py
  dandischema/tests/data/metadata/asset_001.json
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
Labels: patch, release

#25 Fix release workflow
  .github/workflows/release.yml
Labels: internal, release

#26 Delete schema-* tags before running auto
  .github/workflows/release.yml
Labels: internal, release

#27 Add missing "working-directory"
  .github/workflows/release.yml
Labels: internal, release
