Repository dandi/dandi-schema, pull requests merged in 2021-07, with the labels that each got.

#49 Add workflow for testing dandischema against latest release of dandi-cli
  .github/workflows/test-dandi-cli.yml
Labels: tests

#46 fix: change id to indentifier for software
  dandischema/tests/test_datacite.py
Labels: tests

#52 fix: clean up optional components of the schema
  dandischema/consts.py
  dandischema/models.py
  dandischema/tests/data/metadata/asset_001.json
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
Labels: minor

#58 Copy dandietag code from dandi-cli
  dandischema/digests/__init__.py
  dandischema/digests/dandietag.py
  dandischema/digests/tests/__init__.py
  dandischema/digests/tests/test_dandietag.py
Labels: minor

#63 Run dandi-cli tests with dandi-api image built with local version of dandischema
  .github/workflows/test-dandi-cli.yml
  tools/api-with-schema.Dockerfile
Labels: tests

#64 RF(CI): run dandi-cli tests only against 3.8 (but all OSes)
  .github/workflows/test-dandi-cli.yml
Labels: tests

#66 Set DANDI_ALLOW_LOCALHOST_URLS when running dandi-cli tests
  .github/workflows/test-dandi-cli.yml
Labels: tests

#65 Use a generic DOI site instead of 10.80507
  dandischema/models.py
Labels: bug

#60 improve help options
  dandischema/consts.py
  dandischema/metadata.py
  dandischema/models.py
  dandischema/tests/test_models.py
Labels: minor, release

#68 ensure schemaKeys are set properly
  dandischema/consts.py
  dandischema/models.py
  dandischema/tests/test_models.py
Labels: patch, release

#70 Datacite publish argument
  dandischema/datacite.py
  dandischema/tests/test_datacite.py
Labels: patch, release
