Repository dandi/dandi-schema, pull requests merged in 2022-03, with the labels that each got.

#121 Unify version pattern, allow local dandiset URLs
  dandischema/models.py
Labels: release

#123 fix: add type of id to hasMember
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
Labels: minor, release

#125 Update dandi-archive Dockerfile to use Python 3.9
  tools/api-with-schema.Dockerfile
Labels: tests

#126 Directly base Docker image off of dandi-archive image
  tools/api-with-schema.Dockerfile
Labels: tests
