Repository dandi/dandi-schema, pull requests merged in 2022-01, with the labels that each got.

#107 fixing to_datacite: more flexible for urls
  dandischema/datacite.py
  dandischema/tests/test_datacite.py
Labels: minor, release

#112 Various edge case fixes
  dandischema/consts.py
  dandischema/model_types.py
  dandischema/models.py
  dandischema/tests/test_models.py
Labels: patch, release

#117 Specify part generator to DandiETag class
  dandischema/digests/dandietag.py
Labels: release
