Repository dandi/dandi-schema, pull requests merged in 2023-03, with the labels that each got.

#162 Install dandi's `extras` extra when testing
  .github/workflows/test-dandi-cli.yml
Labels: tests

#100 Fully type-annotate and type-check everything
  .github/workflows/test-dandi-cli.yml
  .github/workflows/typing.yml
  README.md
  dandischema/consts.py
  dandischema/datacite.py
  dandischema/digests/dandietag.py
  dandischema/digests/tests/test_dandietag.py
  dandischema/digests/tests/test_zarr.py
  dandischema/digests/zarr.py
  dandischema/exceptions.py
  dandischema/metadata.py
  dandischema/model_types.py
  dandischema/models.py
  dandischema/py.typed
  dandischema/tests/conftest.py
  dandischema/tests/test_datacite.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
  dandischema/tests/test_utils.py
  dandischema/tests/utils.py
  dandischema/utils.py
  setup.cfg
  tox.ini
Labels: minor, release

#163 Fix type annotation of `unvalidated()`
  dandischema/models.py
Labels: patch, release

#165 fix: add 0.6.3 to validation
  dandischema/consts.py
Labels: patch, release
