Repository dandi/dandi-schema, pull requests merged in 2024-08, with the labels that each got.

#247 Move pattern specification for `BaseType.identifier` to the annotation for the `str` type
  dandischema/models.py
Labels: bug, release

#248 Declare `typing_extensions` dependency
  setup.cfg
Labels: dependencies

#175 ENH: adopt sanitize_value from dandi-cli and use for sanitization of identifier
  dandischema/metadata.py
  dandischema/tests/test_utils.py
  dandischema/utils.py
Labels: patch
