Repository dandi/dandi-schema, pull requests merged in 2024-01, with the labels that each got.

#213 OPT: (memory) cache schema files upon first read from github
  dandischema/metadata.py
Labels: performance

#203 Update to supporting Pydantic V2
  dandischema/consts.py
  dandischema/datacite.py
  dandischema/digests/zarr.py
  dandischema/metadata.py
  dandischema/models.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_models.py
  dandischema/tests/test_utils.py
  dandischema/types.py
  dandischema/utils.py
  setup.cfg
Labels: minor, release

#221 Remove unneeded mark to fixture
  dandischema/tests/test_datacite.py
Labels: tests

#218 Allow dictionary representation of `Dandiset` to have extra attributes
  dandischema/consts.py
  dandischema/models.py
Labels: patch, release
