Repository dandi/dandi-schema, pull requests merged in 2025-02, with the labels that each got.

#280 Avoid multiple assignments of constant `ALLOWED_INPUT_SCHEMAS`
  dandischema/consts.py
Labels: internal

#279 Improve `migrate()` in `metadata.py`
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
Labels: bug, patch

#278 Improve (better arguments validation, avoiding repeated creation of validator objects, etc) `_validate_obj_json()` in `metadata.py` and supporting funcs
  dandischema/metadata.py
  dandischema/tests/test_metadata.py
  dandischema/tests/test_utils.py
  dandischema/utils.py
Labels: patch, performance

#290 Remove escaping (\) of : in 2 identifiers regexes
  dandischema/consts.py
  dandischema/models.py
  dandischema/tests/test_metadata.py
Labels: patch
